### ISSUE TITLE
Feedback App Web Issues - 03/04/18

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#148]

**Comment by ZarshaB** [comment]
1>> View Cars
Search Filters: Instead of having filters at the bottom, when customer clicks the filter button, it should open up in a new page (refer to dubizzle and souq search filter). Having filters at the bottom page doesn't make any sense and have never experienced this in any app. It will also be a problem when number of ads increase on the website.

**Comment by ZarshaB** [comment]
2>> When you are viewing ad for particular car, Images in ads have different sizes. Some cover only 30-40% of screen while others cover 70% of screen. Shouldn't they all be of same dimensions and size?

**Comment by ZarshaB** [comment]
3>> When I'm viewing the ad for a particular car, there are search options at the end of the ad. There is no point in having them over there. Infact only Filter button should be at the top right of the ad and when customer clicks it, another page is opened (refer to dubizzle and souq)

**Comment by ZarshaB** [comment]
4>> Refer to other image. When I searched for a particular denomination, I couldn't find the car for that price range. Two things in it:-
1) Please move "No Results Found"(Make "F" of found cpital) a littler lower. It is touching the top banner
2) There is no way to navigate back to any other option. Either it should have a back button or cancel button.
![image](https://user-images.githubusercontent.com/35685146/38237169-d8d761b0-373f-11e8-903e-e167e3a9e042.png)

**Comment by ZarshaB** [comment]
5>> All headings like Terms & Conditions, FAQs etc shoould be moved a littler lower. They r touching the top banner

**Comment by ZarshaB** [comment]
6>> Contact Us
Mobile number is taking dots and dashes. 

**Already Fixed**

**Comment by ZarshaB** [comment]
7>> There is no option to view my ad in My Ads section. By clicking on My Ad, customer should be able to view his full ad.

**Comment by ZarshaB** [comment]
8>> **My Favorites**
When I click on the Ad title, it is opening the ad in browser. It should be opened in the app.

**Comment by ZarshaB** [comment]
9>> **My Account**
Just like website, when customer selects any option and it opens, there should be a grey bar having all five options for My Account.

**Comment by ZarshaB** [comment]
10>> **Purchase History**
Car Name should be read as Ad Title. Same error in website. Please rectify everywhere.
Separately Logged Issue link = https://github.com/asifjans/Inovedia/issues/146

**Comment by ZarshaB** [comment]
11>> **Purchase History**
When I click on the Ad title, it is opening the ad in browser. It should be opened in the app.

**Comment by ZarshaB** [comment]
12>> **Purchase History**
When I click on e-Ticket, it is opening in browser. It should open in app.

**Comment by ZarshaB** [comment]
13>> **Purchase History** 
When I click "I" in status, the window that opens is totally dis aligned and I don’t know how to close it. Please refer to picture attached.

**Comment by ZarshaB** [comment]
14>> Please refer to attached picture. What is this grey line doing in reasons for deleting the ad?
![image](https://user-images.githubusercontent.com/35685146/38237560-fc818400-3740-11e8-82e1-daa34e7b4018.png)

**Comment by ZarshaB** [comment]
15>> **Buy Ticket**
Please refer to attached picture. Under Image heading, there is no image.

**Comment by ZarshaB** [comment]
16>> **Buy Ticket**
Please refer to attached picture. First I have clicking option, then payment summary and then T&Cs on which I'm clicking. It should be Payment summary and then click option and T&Cs.
![image](https://user-images.githubusercontent.com/35685146/38237691-5127db62-3741-11e8-888e-cda38f657b2b.png)

**Comment by ZarshaB** [comment]
11>> In Billing address, I did not expand the option and clicked check out. It took me to payment gateway without prompting for entering city and Billing address. Something happened in website when I collapsed the Billing info. It took me directly to checkout without prompting for entering the info. Please rectify everywhere.

Separately logged ticket link = https://github.com/asifjans/Inovedia/issues/145

**Comment by ZarshaB** [comment]
12>> **Buy Ticket**
Please refer to attached picture. In selecting the months and year for Card, only 2-3 options and rest I scroll them abnormally. Please fix it and make it look normal.
![image](https://user-images.githubusercontent.com/35685146/38237809-a2510bc6-3741-11e8-9221-14c76d720a28.png)

**Comment by ZarshaB** [comment]
**Re-opened**
4>> No cancel button. 
![image](https://user-images.githubusercontent.com/35685146/38375610-10ac6d84-3910-11e8-9587-031fb922dbb3.png)

**Comment by ZarshaB** [comment]
13>> Share button is not working on Car detail page. :o

**Comment by ZarshaB** [comment]
14>> Button is overlapping with banner.
![image](https://user-images.githubusercontent.com/35685146/38376069-353b5e52-3911-11e8-92c8-a1f093965f9b.png)

**Comment by ZarshaB** [comment]
15>> Radio buttons are not good.
![image](https://user-images.githubusercontent.com/35685146/38376330-c27b874c-3911-11e8-8b72-7c2c284164d4.png)

**Comment by ZarshaB** [comment]
16>> Not saving Hear About Us field.
![image](https://user-images.githubusercontent.com/35685146/38376372-da495138-3911-11e8-90b6-2bee1755fa6d.png)

**Comment by ZarshaB** [comment]
**Re-opened**
4>> No cancel button. 
![image](https://user-images.githubusercontent.com/35685146/38375610-10ac6d84-3910-11e8-9587-031fb922dbb3.png)

11>> Purchase History ** Not FIXED**
When I click on the Ad title, it is opening the ad in browser. It should be opened in the app.

2,3>> There should be separate page of filter. 

Resolved issues are removed.

**Comment by ZarshaB** [comment]
13>> Share button is not working on Car detail page.  **Not Fixed**
![image](https://user-images.githubusercontent.com/35685146/38376030-191f9648-3911-11e8-8a0e-340b6ea310ef.png)

**Comment by ZarshaB** [comment]
17>> Please make it properly aligned.
![image](https://user-images.githubusercontent.com/35685146/38415652-97188326-39ab-11e8-8aa0-3684e2766925.png)

18>> After purchasing it redirects me to this page.
![image](https://user-images.githubusercontent.com/35685146/38415676-b57bfe88-39ab-11e8-9f5a-dcca8d573c79.png)

On clicking on back button it take me to this page. And when I click on cart, item is still there and not purchased. 
![image](https://user-images.githubusercontent.com/35685146/38415713-c996b660-39ab-11e8-9b9c-1036194be440.png)

**Comment by ZarshaB** [comment]
1>> View Cars
Search Filters: Instead of having filters at the bottom, when customer clicks the filter button, it should open up in a new page (refer to dubizzle and souq search filter). Having filters at the bottom page doesn't make any sense and have never experienced this in any app. It will also be a problem when number of ads increase on the website. **(Reopened)**

**Comment by ZarshaB** [comment]
2>> **(Comment is added on separately log ticket)** When you are viewing ad for particular car, Images in ads have different sizes. Some cover only 30-40% of screen while others cover 70% of screen. Shouldn't they all be of same dimensions and size?

Separately Logged Issue link = https://github.com/asifjans/Inovedia/issues/149

**Comment by ZarshaB** [comment]
3>> **(Haider)** When I'm viewing the ad for a particular car, there are search options at the end of the ad. There is no point in having them over there. Infact only Filter button should be at the top right of the ad and when customer clicks it, another page is opened (refer to dubizzle and souq) **(Reopened)**

**Comment by asifjans** [comment]
1>> View Cars
Search Filters: Instead of having filters at the bottom, when customer clicks the filter button, it should open up in a new page (refer to dubizzle and souq search filter). Having filters at the bottom page doesn't make any sense and have never experienced this in any app. It will also be a problem when number of ads increase on the website. 
2>> (Comment is added on separately log ticket) When you are viewing ad for particular car, Images in ads have different sizes. Some cover only 30-40% of screen while others cover 70% of screen. Shouldn't they all be of same dimensions and size?

Separately Logged Issue link = #149

3>> (Haider) When I'm viewing the ad for a particular car, there are search options at the end of the ad. There is no point in having them over there. Infact only Filter button should be at the top right of the ad and when customer clicks it, another page is opened (refer to dubizzle and souq) (Reopened)

**Comment by asifjans** [comment]
1>> **(RFR-Haider)** View Cars
Search Filters: Instead of having filters at the bottom, when customer clicks the filter button, it should open up in a new page (refer to dubizzle and souq search filter). Having filters at the bottom page doesn't make any sense and have never experienced this in any app. It will also be a problem when number of ads increase on the website.

3>> **(RFR-Haider)** When I'm viewing the ad for a particular car, there are search options at the end of the ad. There is no point in having them over there. Infact only Filter button should be at the top right of the ad and when customer clicks it, another page is opened (refer to dubizzle and souq) (Reopened)

**Comment by asifjans** [comment]
1>>**"Fixed"** View Cars
Search Filters: Instead of having filters at the bottom, when customer clicks the filter button, it should open up in a new page (refer to dubizzle and souq search filter). Having filters at the bottom page doesn't make any sense and have never experienced this in any app. It will also be a problem when number of ads increase on the website.

3>>**"Fixed"**  When I'm viewing the ad for a particular car, there are search options at the end of the ad. There is no point in having them over there. Infact only Filter button should be at the top right of the ad and when customer clicks it, another page is opened (refer to dubizzle and souq) (Reopened)

**Comment by ZarshaB** [comment]
Now it is okay but please make space from above as it is for other pages.
![image](https://user-images.githubusercontent.com/35685146/38612585-a0d090f4-3da0-11e8-8c9e-3075ea262ee7.png)

**Comment by ZarshaB** [comment]
1>> My Ads page, ads is opening in browser. It was fixed but now it is opening in browser.

**Comment by ZarshaB** [comment]
2>> Size of all pages from above is disturbed. It was fixed by Anum before but again it's size has changed for all pages.

**Comment by Anum444** [comment]
1>> My Ads page, ads is opening in browser. It was fixed but now it is opening in browser.  **Fixed**

**Comment by Anum444** [comment]
2>> **RFR** Size of all pages from above is disturbed. It was fixed by Anum before but again it's size has changed for all pages.

**Comment by ZarshaB** [comment]
2>> All other pages have same space except for Account Pages(My Favorites, My Ads, Purchase History, Reward Points). They have more space.

**Comment by Anum444** [comment]
@Anum444
2>> All other pages have same space except for Account Pages(My Favorites, My Ads, Purchase History, Reward Points). They have more space.   **RFR**
