### ISSUE TITLE
Feedback - Message change

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#155]

**Comment by sammiullah** [comment]
Please refer to attached image. The message needs to be read as follows:-(proper format and center aligned)   **FIXED**

                                         Oooopss!!!

We thought so too but due to some mumbo-jumbo, you can enter Rewards Points only in multiples of 100.

![image](https://user-images.githubusercontent.com/35685146/38352305-2f965b5e-38cc-11e8-9ffd-2213bfc1f5e1.png)
