### ISSUE TITLE
Add to Favorites. 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#237]

**Comment by ZarshaB** [comment]
Without login if I click on Add to Favorites icon then it displays me message to login/Register to continue.
If I cross that pop up then it does not allow me to click. It should again show me this message instead of making that in clickable.
Seeing this everywhere for Ad to Favorites icon.

![image](https://user-images.githubusercontent.com/35685146/39635239-524f900e-4fd6-11e8-8fe7-ba60132738cb.png)

**Comment by Anum444** [comment]
**Fixed**

Without login if I click on Add to Favorites icon then it displays me message to login/Register to continue.
If I cross that pop up then it does not allow me to click. It should again show me this message instead of making that in clickable.
Seeing this everywhere for Ad to Favorites icon.

**Comment by ZarshaB** [comment]
Fixed for View Cars but not for Car Detail page.

**Comment by Anum444** [comment]
**Fixed**

Fixed for View Cars but not for Car Detail page.
