### ISSUE TITLE
Client's Feed back - Feb192018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#94]

**Comment by ZarshaB** [comment]
1>> Please make it "to" or "-" instead of "<".
![image](https://user-images.githubusercontent.com/35685146/36386030-4231e58c-15b6-11e8-9009-6801f340fcb2.png)

**Comment by ZarshaB** [comment]
2>> Fav icon is stretched.

**Comment by ZarshaB** [comment]
3>> It would be mail to text.
![image](https://user-images.githubusercontent.com/35685146/36386085-6379e744-15b6-11e8-9f3a-26376f753388.png)

**Comment by ZarshaB** [comment]
4>> It is "Privacy Policy".
![image](https://user-images.githubusercontent.com/35685146/36386100-758ccd8e-15b6-11e8-9a32-03bc933a389d.png)

**Comment by ZarshaB** [comment]
5>> Remove this dot.
![image](https://user-images.githubusercontent.com/35685146/36386115-87199f82-15b6-11e8-87e3-af3a4556fdcd.png)

**Comment by ZarshaB** [comment]
6>> If wrong email is entered then Contact Us redirects to blank page.

**Comment by ZarshaB** [comment]
7>> There should be delete option.
![image](https://user-images.githubusercontent.com/35685146/36386190-bc256436-15b6-11e8-8e1d-f3c7937951d4.png)

**Comment by ZarshaB** [comment]
8>> There should be ticket price instead of Car price.
![image](https://user-images.githubusercontent.com/35685146/36386210-d32b1bb2-15b6-11e8-937a-9e3593e0a2ca.png)
![image](https://user-images.githubusercontent.com/35685146/36386225-deec2a72-15b6-11e8-9aa5-720da059284d.png)

**Comment by ZarshaB** [comment]
9>> In "My Ads" there should be disable delete option if Car sold.

**Comment by ZarshaB** [comment]
10>> Remove decimals.
![image](https://user-images.githubusercontent.com/35685146/36386270-07515640-15b7-11e8-9431-ac83dceb92d9.png)

**Comment by ZarshaB** [comment]
11>> Page should be a/c to ticket.
![image](https://user-images.githubusercontent.com/35685146/36386315-2738f148-15b7-11e8-85c4-e22381d9819c.png)

**Comment by ZarshaB** [comment]
12>> Tool tips does not disappear if I click on it.
![image](https://user-images.githubusercontent.com/35685146/36386351-4e24a356-15b7-11e8-871c-400cb9c6ee00.png)

**Comment by ZarshaB** [comment]
13>> For Order Summary page and Place your Ad page terms and conditions should be on the same page instead of redirecting to another page. Only main terms and conditions should be redirect.

**Comment by ZarshaB** [comment]
14>> When Admin change status of car to "Sold" then status of car on View Cars page should be "Sold out".

**Comment by ZarshaB** [comment]
15>> Change it to "View More".
![image](https://user-images.githubusercontent.com/35685146/36386608-186bcdce-15b8-11e8-88ef-aa066a58f7b8.png)

**Comment by ZahidRavian** [comment]
**These issues are fixed**
1>> Please make it "to" or "-" instead of "<".
3>> It would be mail to text.
4>> It is "Privacy Policy".
5>> Remove this dot.
6>> If wrong email is entered then Contact Us redirects to blank page.
8>> There should be ticket price instead of Car price.
9>> In "My Ads" there should be disable delete option if Car sold.
10>> Remove decimals.
12>> Tool tips does not disappear if I click on it.
13>> For Order Summary page and Place your Ad page terms and conditions should be on the same page instead of redirecting to another page. Only main terms and conditions should be redirect.
15>> Change it to "View More".

**Pending Issues are**
2>> Fav icon is stretched.
7>> There should be delete option.
11>> Page should be a/c to ticket.
14>> When Admin change status of car to "Sold" then status of car on View Cars page should be "Sold out".

**Comment by ZarshaB** [comment]
14>>Please change this price to ticket price.
![image](https://user-images.githubusercontent.com/35685146/36413187-2136d818-163f-11e8-8189-c783da3c8bbf.png)

**Comment by ZarshaB** [comment]
15>> It should be orange as we are displaying all links with orange color.
![image](https://user-images.githubusercontent.com/35685146/36413227-448ca4dc-163f-11e8-9f75-6066dda0f690.png)

**Comment by ZarshaB** [comment]
16>> It would be:
By clicking on Checkout, I agree to the following: - 
![image](https://user-images.githubusercontent.com/35685146/36413333-b638c19c-163f-11e8-9b3b-c2e0586280ea.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36413350-c25578d0-163f-11e8-898d-ec9532aba37e.png)

**Comment by ZarshaB** [comment]
17>> Also Terms and conditions should be there:
By clicking on Save, I agree to the following: - 
![image](https://user-images.githubusercontent.com/35685146/36413377-effd7fd0-163f-11e8-8f80-636776d207ae.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/36413404-10e75a54-1640-11e8-8c94-868d68b5a5ee.png)

**Comment by ZarshaB** [comment]
18>> Please change it to "Points" instead of "Point".
![image](https://user-images.githubusercontent.com/35685146/36413487-698d05b4-1640-11e8-89ca-efb9cc41bd77.png)

**Comment by ZarshaB** [comment]
19>> Please also remove space.
![image](https://user-images.githubusercontent.com/35685146/36413816-cd08e418-1641-11e8-8263-0a9838c74a4f.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36413808-c3d46138-1641-11e8-8908-cc4eb1b15102.png)

**Comment by ZahidRavian** [comment]
**These issues are fixed and ready for testing**
2>> Fav icon is stretched.
11>> Page should be a/c to ticket.
14>>Please change this price to ticket price. 
15>> It should be orange as we are displaying all links with orange color.
16>> It would be: By clicking on Checkout, I agree to the following. 
17>> Also Terms and conditions should be there on Place your Ad page:
18>> Please change it to "Points" instead of "Point".
19>> Please also remove space.

**Comment by ZarshaB** [comment]
11>> It is appearing like this for me:
![image](https://user-images.githubusercontent.com/35685146/36422376-8ef203aa-165d-11e8-8cfa-fb56e63b4ecb.png)

**Comment by shayanr262** [comment]
hi

**Comment by ZahidRavian** [comment]
**This issue is fixed and ready for testing**

11>> It is appearing like this for me:

**Comment by ZarshaB** [comment]
11>> Please also remove it from downwards.
![image](https://user-images.githubusercontent.com/35685146/36484449-29a6ec16-173b-11e8-9adb-2226e9b99d8e.png)
