### ISSUE TITLE
Pending Task List

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#99]

**Comment by asifjans** [comment]
0) Client Feedback
1) UI - Task On High Priority High
2) UI - Functional task High
3) Responsive

**Comment by Anum444** [comment]
**1. Client's Feedback 23-02-2018  #98**

**Low priority**
1>> In How it works, when customer presses learn more of clicks on HOW it Works, then it should be routed to the page and should stay there for 1.5-2 seconds and then video should start playing in full screen. Currently, when I go to that page, only 20% video is visible and its hard to find the play bar.

2>> Email Templates for these:
Docs
Email Template to Successfull Seller.docx
Price Denomination.docx

Ticket Refund Content.docx
Ticket Transfer Content.docx
Winner Email Template.docx
Contact Us page.docx

6>> When customer sends an email to info@weladela.com, then he should get the same email as he got by submitting enquiry form.

7>> It would be according to page.

**Comment by Anum444** [comment]
**2. UI - Task On High Priority #91**

18>> Footer icons and cart icon is appearing blurry. **(Anum)**

20>> Please check this, when I upload any file then it changes it's place and then goes to right place.
Video Link = https://www.screencast.com/t/mwjSU3Yck

16>> Please remove space for error message and field.And also make labels equal to field.

**Comment by Anum444** [comment]
**3. UI - Functional task #87**

59 >> if the customer wins a luck draw, then all his points will be forfeited and his balance will be zero.**(Zahid)** 

60>>  In case of Ticket Transfer , then for Purchase history: **(Zahid)**
If the Ticket Type is Transferred, then Date will be of transfer date, Price will be 0 and payment method will be N/A.

65>>  It should be 6 days, 23 hours , 59 minutes and 60 seconds as I activate ad. Whereas it displays time with hours remaining of present day. **(Zahid)**

73>> This email template is having old domain of email. **(this is only for testing purpose)**

60>>  I purchased a ticket of Ad "Alfa Romeo 4c" and transferred that to "Lotus esprit s2". But In Purchase History it removed my history for "Alfa Romeo 4C" and in place of that it is showing new record of ad to which ticket is being transferred. **(Zahid)**

66>> On Refund it should change status in Reward points as "Cancelled due to refund". And also on refund reward points earned from that specific ticket should be subtracted from total reward points. **(Zahid)** 

69>> Images are accepting files also. It should only accept images. **(Haider)**
